---
name: ktuberling
version: 17.08.1
summary: A simple constructor game suitable for children and adults alike
description: |-
    KTuberling is a drawing toy for small children with several activites.

    \* Give the potato a funny face, clothes, and other goodies \* Build a small town, complete with school, zoo, and fire department \* Create a fantastic moonscape with spaceships and aliens

    KTuberling can speak the name of each the object in several languages, to assist in learning basic vocabulary.

    This package is part of the KDE games module.
confinement: strict
grade: stable
apps:
    ktuberling:
        command: kf5-launch ktuberling
        plugs:
        - kde-frameworks-5-plug
        - home
        - x11
        - opengl
        - network
        - network-bind
        - unity7
        - pulseaudio
slots:
    session-dbus-interface:
        interface: dbus
        name: org.kde.ktuberling
        bus: session
plugs:
    kde-frameworks-5-plug:
        content: kde-frameworks-5-all
        interface: content
        default-provider: kde-frameworks-5
        target: kf5
parts:
    ktuberling:
        after:
        - kde-frameworks-5-dev
        - kde-frameworks-5-env
        plugin: cmake
        build-packages:
        - libkf5kdegames-dev
        - libkf5kdelibs4support-dev
        - libphonon4qt5-dev
        - libphonon4qt5experimental-dev
        - libpulse0
        source: https://download.kde.org/stable/applications/17.08.1/src/ktuberling-17.08.1.tar.xz
        configflags:
        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
        - "-DCMAKE_INSTALL_PREFIX=/usr"
        - "-DCMAKE_BUILD_TYPE=Release"
        - "-DENABLE_TESTING=OFF"
        - "-DBUILD_TESTING=OFF"
        - "-DKDE_SKIP_TEST_SETTINGS=ON"
